version: '2.4'
services:
  rabbitmq:
    image: rabbitmq:3.7.14-management
    ports:
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 5s
      timeout: 15s
      retries: 10

  storage_leader:
    build: storage/
    command: python3 -u ./storage.py
    environment:
      ROLE: leader
    depends_on:
      rabbitmq:
        condition: service_healthy

  storage_replica:
    build: storage/
    command: python3 -u ./storage.py
    environment:
      ROLE: replica
    depends_on:
      rabbitmq:
        condition: service_healthy
